### PR TITLE
dropdown searchbar for Learn page

### PR DESCRIPTION
**Pull request by lottihill**
I have added a dropdown search bar to the learn page so that users can search for documentation easily. I did my best to copy the existing style of the page, and tested out the links to make sure they go to the right pages.

This links to issue #35

### CODE REVIEW

**Comment by quinton-ashley** [comment]
@lottihill Great work on this!! 🙌 I like that you matched the styles. I adjusted them a bit so that it'll work with the dark mode of the site as well though.

I think it'd be nice to add the dropdown search to every Learn page in the nav bar. There could be a search icon in the nav bar and when users click on it the search input would expand and the page nav links in the nav bar would be hidden.

But for the `learn/index.html` page it's a bit hard to look at the dropdown with all the reference links behind it. I think it'd be better if, instead of showing a dropdown, the search filtered through the links on the page.

Do you think these are good ideas? Would you be down to try and implement these features?

**Comment by lottihill** [comment]
Hi, thanks for the feedback, so we're talking about something like this?
PXL_20240425_152642774 MP~2
I'd be happy to give it my best shot :)

**Comment by quinton-ashley** [comment]
yes exactly! That would be great 😄

**Comment by quinton-ashley** [comment]
Hi @lottihill are you still interested in working on this?

**Comment by lottihill** [comment]
Hi @quinton-ashley yes! I've only started yesterday though, I've had other uni projects to complete

**Pull request merged**
